name: Node.js App Deploy

on: 
  issues:
    types: [opened]

jobs:
  deploy:
    runs-on:  nodejsapp-runner 
    steps:
      - name: checkout del repositorio
        uses: actions/checkout@v4.1.4

      - name: Desplegar la aplicacion
        run: pm2 restart nodejsapp